In [1]:
import gym
import numpy as np
import inventory_model
from evaluate import *

In [2]:
CONFIG = {'h': 1, 'p': 1, 'L': 10, 'max_demand': 6, 'max_inventory': 100}
ContCONFIG = {'h': 1, 'p': 1, 'L': 10, 'lambda': 1}

In [3]:
env = gym.make('inventory_model-v0', config=CONFIG)
cont_env = gym.make('inventory_cont_model-v0', config=ContCONFIG)

In [4]:
print(env.state)
print(env.action_space)
print(env.observation_space) # openAI calles states observations :/

print(cont_env.state)
print(cont_env.action_space)
print(cont_env.observation_space)

[0 0 0 0 0 0 0 0 0 0 0]
Discrete(101)
MultiDiscrete([101 101 101 101 101 101 101 101 101 101 101])
[0 0 0 0 0 0 0 0 0 0 0]
Box(0.0, inf, (1, 1), float32)
Box(0.0, inf, (11, 1), float32)


In [5]:
print(cont_env.action_space.sample())
print(env.action_space.sample())
print('***')

env.state = np.array([0]*(CONFIG['L']+1))
print(env.step(1))
print('***')

cont_env.state = np.array([0]*(CONFIG['L']+1))
print(cont_env.step(np.array([[1.0]])))
print('***')

[[0.06502642]]
66
***
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), -4)
***
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), array([-1.5902926]))
***


The following cell defines the random policy model and the constant policy model, and then calls the evaluate function. When ordering constant 1 or 2, the policy is stable.

In [6]:
def random_model(env):
    def policy(state):
        return env.action_space.sample()
    return policy

In [7]:
numiter = 2000
print ('discrete state space with Bernoulli demand under random policy:')
evaluate(random_model, env, numiter)
print()
print ('continuous state space with Exp(1) demand under random policy:')
evaluate(random_model, cont_env, numiter)
print()

for i in range(1,6):
    def constant_model(env):
        def policy(state):
            return i
        return policy
    print ('discrete state space under constant %s order policy:' %i)
    evaluate(constant_model, env, numiter)
    print()
    
for i in range(1,3):
    def constant_model(env):
        def policy(state):
            return np.array([[i]])
        return policy
    print ('continuous state space under constant %s order policy:' %i)
    evaluate(constant_model, cont_env, numiter)
    print()

discrete state space with Bernoulli demand under random policy:
mean:  -99.38785
standard deviation: 0.03376836537352638

continuous state space with Exp(1) demand under random policy:
mean:  -0.9844401595885601
standard deviation: 0.03346088702510928

discrete state space under constant 1 order policy:
mean:  -2.03905
standard deviation: 0.0289537994052594

discrete state space under constant 2 order policy:
mean:  -1.3386
standard deviation: 0.02629144347501675

discrete state space under constant 3 order policy:
mean:  -24.728599999999997
standard deviation: 11.545075566664776

discrete state space under constant 4 order policy:
mean:  -96.91569999999999
standard deviation: 0.3540352524820092

discrete state space under constant 5 order policy:
mean:  -98.27284999999999
standard deviation: 0.15121789741958386

continuous state space under constant 1 order policy:
mean:  -0.37452468899018043
standard deviation: 0.016850968559312555

continuous state space under constant 2 order polic