In [1]:
import gym
import numpy as np
import inventory_model
from evaluate import *

In [2]:
CONFIG = {'h': 1, 'p': 1, 'L': 10, 'max_demand': 6, 'max_inventory': 100}
ContCONFIG = {'h': 1, 'p': 1, 'L': 10, 'lambda': 1}

In [3]:
env = gym.make('inventory_model-v0', config=CONFIG)
cont_env = gym.make('inventory_cont_model-v0', config=ContCONFIG)

In [4]:
print(env.state)
print(env.action_space)
print(env.observation_space) # openAI calles states observations :/

print(cont_env.state)
print(cont_env.action_space)
print(cont_env.observation_space)

[0 0 0 0 0 0 0 0 0 0 0]
Discrete(101)
MultiDiscrete([101 101 101 101 101 101 101 101 101 101 101])
[0 0 0 0 0 0 0 0 0 0 0]
Box(0.0, inf, (1, 1), float32)
Box(0.0, inf, (11, 1), float32)


In [15]:
env.state = np.array([0]*(CONFIG['L']+1))
print(env.step(1))
print('***')

cont_env.state = np.array([0]*(CONFIG['L']+1))
print(cont_env.step(np.array([[1.0]])))
print('***')

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), -2)
***
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), array([-1.90763977]))
***


The following cell defines the random policy model and the constant policy model, and then calls the evaluate function. When ordering constant 1 or 2, the policy is stable.

In [8]:
def random_model(env):
    def policy(state):
        return env.action_space.sample()
    return policy

In [10]:
numiter = 200000
print ('discrete state space with Bernoulli demand under random policy:')
evaluate(random_model, env, numiter)
print ('discrete state space with Exp(1) demand under random policy:')
evaluate(random_model, cont_env, numiter)

for i in range(1,6):
    def constant_model(env):
        def policy(state):
            return i
        return policy
    print ('discrete state space under constant %s order policy:' %i)
    evaluate(constant_model, env, numiter)
    
for i in range(1,3):
    def constant_model(env):
        def policy(state):
            return np.array([[i]])
        return policy
    print ('continuous state space under constant %s order policy:' %i)
    evaluate(constant_model, cont_env, numiter)

discrete state space with Bernoulli demand under random policy:
mean:  -99.92490000000001
standard deviation: 0.000776347216134522
discrete state space with Exp(1) demand under random policy:
mean:  -1.0010243147165616
standard deviation: 0.003534807488712142
discrete state space under constant 1 order policy:
mean:  -2.0319595
standard deviation: 0.001761082692550229
discrete state space under constant 2 order policy:
mean:  -1.331876
standard deviation: 0.002696403901495486
discrete state space under constant 3 order policy:
mean:  -50.8456705
standard deviation: 2.035929344298875
discrete state space under constant 4 order policy:
mean:  -99.7462825
standard deviation: 0.005149401542899044
discrete state space under constant 5 order policy:
mean:  -99.964106
standard deviation: 0.0016554845212186113
continuous state space under constant 1 order policy:


AttributeError: 'int' object has no attribute 'shape'

In [14]:
cont_env.action_space.sample()

array([[1.3967148]], dtype=float32)